// ─────────────────────────────────────────────────────────────
// diffords.js – Non-IBA cocktails from Difford's Guide
// Organized by morphological family for the Academy mode.
// ─────────────────────────────────────────────────────────────

export const DIFFORDS_COCKTAILS = [

  // ═══ HIGHBALL FAMILY (8) ═══════════════════════════════════

  {
    name: "Gin & Tonic",
    category: "Difford's Classics",
    family: "Highball",
    glass: "Vaso Highball",
    method: "Construido",
    garnish: "Rodaja de lima o limón",
    color: "#D4E6B5",
    icon: "🫧",
    ingredients: ["50ml Ginebra", "150ml Agua tónica", "Hielo"],
    story: 'Nacido en la India colonial británica, la tónica con quinina combatía la malaria. Añadir ginebra lo convirtió en el aperitivo por excelencia.',
  },
  {
    name: "Tom Collins",
    category: "Difford's Classics",
    family: "Highball",
    glass: "Vaso Collins",
    method: "Agitado y completado con soda",
    garnish: "Rodaja de limón y cereza",
    color: "#F5F0C1",
    icon: "🍋",
    ingredients: ["45ml Ginebra Old Tom", "30ml Zumo de limón", "15ml Jarabe simple", "Soda"],
    story: 'Popularizado en el siglo XIX, lleva el nombre de un camarero del Limmer\'s Hotel de Londres. Usa ginebra Old Tom, más dulce que la London Dry.',
  },
  {
    name: "Whiskey Highball",
    category: "Difford's Classics",
    family: "Highball",
    glass: "Vaso Highball",
    method: "Construido",
    garnish: "Sin decoración",
    color: "#D4A950",
    icon: "🥃",
    ingredients: ["45ml Whisky japonés", "120ml Soda", "Hielo"],
    story: 'Elevado a arte en Japón, donde se prepara con precisión milimétrica: hielo tallado a mano, soda vertida por la pared del vaso y una sola vuelta de cuchara.',
  },
  {
    name: "El Diablo",
    category: "Difford's Classics",
    family: "Highball",
    glass: "Vaso Highball",
    method: "Construido",
    garnish: "Rodaja de lima",
    color: "#8B1A1A",
    icon: "😈",
    ingredients: ["45ml Tequila Reposado", "15ml Crème de Cassis", "15ml Zumo de lima", "Ginger beer"],
    story: 'Cóctel mexicano de los años 40 que combina tequila con cassis y ginger beer. Su color rojizo le da el nombre diabólico.',
  },
  {
    name: "Harvey Wallbanger",
    category: "Difford's Classics",
    family: "Highball",
    glass: "Vaso Highball",
    method: "Construido",
    garnish: "Rodaja de naranja",
    color: "#FF9F00",
    icon: "🏄",
    ingredients: ["45ml Vodka", "90ml Zumo de naranja", "15ml Galliano"],
    story: 'Icono de los años 70, nombrado supuestamente por un surfista californiano. Es básicamente un Screwdriver coronado con licor Galliano.',
  },
  {
    name: "Garibaldi",
    category: "Difford's Classics",
    family: "Highball",
    glass: "Vaso Highball",
    method: "Construido",
    garnish: "Rodaja de naranja",
    color: "#E85D26",
    icon: "🍊",
    ingredients: ["45ml Campari", "120ml Zumo de naranja (fluffy)"],
    story: 'Nombrado por Giuseppe Garibaldi, héroe de la unificación italiana. La clave es batir el zumo de naranja hasta que quede espumoso.',
  },
  {
    name: "Gin Rickey",
    category: "Difford's Classics",
    family: "Highball",
    glass: "Vaso Highball",
    method: "Construido",
    garnish: "Media lima exprimida",
    color: "#C8DFC3",
    icon: "🫧",
    ingredients: ["60ml Ginebra", "15ml Zumo de lima", "Soda"],
    story: 'Creado en Washington D.C. en los 1880s para el coronel Joe Rickey. Sin azúcar añadido, es un highball seco y refrescante.',
  },
  {
    name: "Presbyterian",
    category: "Difford's Classics",
    family: "Highball",
    glass: "Vaso Highball",
    method: "Construido",
    garnish: "Twist de limón",
    color: "#C9A85C",
    icon: "⛪",
    ingredients: ["60ml Whisky escocés", "60ml Ginger ale", "60ml Soda"],
    story: 'Highball sobrio y elegante, mezcla whisky con partes iguales de ginger ale y soda. Ideal para quien busca un trago largo y suave.',
  },

  // ═══ SOUR FAMILY (10) ═════════════════════════════════════

  {
    name: "Gold Rush",
    category: "Difford's Classics",
    family: "Sour",
    glass: "Old Fashioned (Rocks)",
    method: "Agitado y colado",
    garnish: "Twist de limón",
    color: "#D4A520",
    icon: "🍯",
    ingredients: ["60ml Bourbon", "22ml Jarabe de miel", "22ml Zumo de limón"],
    story: 'Creado por T.J. Siegal en Milk & Honey, NYC (2001). Reemplaza el jarabe simple del Whiskey Sour por miel, aportando profundidad y suavidad.',
  },
  {
    name: "Amaretto Sour",
    category: "Difford's Classics",
    family: "Sour",
    glass: "Old Fashioned (Rocks)",
    method: "Dry shake y agitado",
    garnish: "Cereza al marrasquino y piel de naranja",
    color: "#C47D2B",
    icon: "🍒",
    ingredients: ["45ml Amaretto", "22ml Bourbon", "30ml Zumo de limón", "15ml Jarabe simple", "15ml Clara de huevo"],
    story: 'Jeffrey Morgenthaler redefinió este cóctel añadiendo bourbon y clara de huevo, transformándolo de bebida empalagosa a sour sofisticado.',
  },
  {
    name: "Gimlet",
    category: "Difford's Classics",
    family: "Sour",
    glass: "Copa de Cóctel",
    method: "Agitado y colado",
    garnish: "Rodaja de lima",
    color: "#B8D9A0",
    icon: "💚",
    ingredients: ["60ml Ginebra", "30ml Cordial de lima (Rose's)"],
    story: 'Originado en la Royal Navy para prevenir el escorbuto. El debate eterno: ¿cordial o zumo fresco? Raymond Chandler lo inmortalizó en su novela.',
  },
  {
    name: "Jack Rose",
    category: "Difford's Classics",
    family: "Sour",
    glass: "Copa de Cóctel",
    method: "Agitado y colado",
    garnish: "Twist de limón",
    color: "#E84060",
    icon: "🌹",
    ingredients: ["60ml Applejack o Calvados", "22ml Zumo de lima", "15ml Granadina"],
    story: 'Cóctel pre-Prohibición que aparece en obras de Hemingway y Steinbeck. La granadina artesanal le da su icónico color rosado.',
  },
  {
    name: "Brown Derby",
    category: "Difford's Classics",
    family: "Sour",
    glass: "Copa de Cóctel",
    method: "Agitado y colado",
    garnish: "Twist de pomelo",
    color: "#C8A050",
    icon: "🎩",
    ingredients: ["60ml Bourbon", "30ml Zumo de pomelo", "15ml Jarabe de miel"],
    story: 'Nombrado por el famoso restaurante en forma de sombrero en Los Ángeles. El pomelo aporta un amargor elegante que equilibra la miel.',
  },
  {
    name: "Ward Eight",
    category: "Difford's Classics",
    family: "Sour",
    glass: "Copa de Cóctel",
    method: "Agitado y colado",
    garnish: "Rodaja de naranja y cereza",
    color: "#D4603A",
    icon: "🗳️",
    ingredients: ["60ml Whiskey de centeno", "22ml Zumo de limón", "22ml Zumo de naranja", "10ml Granadina"],
    story: 'Creado en 1898 en Boston para celebrar una victoria electoral. Combina centeno con cítricos duales y un toque de granadina.',
  },
  {
    name: "Fitzgerald",
    category: "Difford's Classics",
    family: "Sour",
    glass: "Copa de Cóctel",
    method: "Agitado y colado",
    garnish: "Rodaja de limón",
    color: "#D0D88C",
    icon: "📖",
    ingredients: ["45ml Ginebra", "22ml Zumo de limón", "15ml Jarabe simple", "2 dashes Angostura"],
    story: 'Creado por Dale DeGroff. Es un Gin Sour perfeccionado con bitters, nombrado en honor a F. Scott Fitzgerald.',
  },
  {
    name: "Whiskey Smash",
    category: "Difford's Classics",
    family: "Sour",
    glass: "Old Fashioned (Rocks)",
    method: "Macerado y agitado",
    garnish: "Ramita de menta y rodaja de limón",
    color: "#B89040",
    icon: "🌿",
    ingredients: ["60ml Bourbon", "22ml Zumo de limón", "15ml Jarabe simple", "4 hojas de menta", "2 gajos de limón"],
    story: 'Dale DeGroff lo popularizó como un Mint Julep deconstruido. Macerar la menta y el limón libera aceites esenciales aromáticos.',
  },
  {
    name: "Army & Navy",
    category: "Difford's Classics",
    family: "Sour",
    glass: "Copa de Cóctel",
    method: "Agitado y colado",
    garnish: "Twist de limón",
    color: "#C8C0A0",
    icon: "⚓",
    ingredients: ["60ml Ginebra", "30ml Zumo de limón", "22ml Orgeat"],
    story: 'Cóctel militar de la era pre-Prohibición. El orgeat (jarabe de almendra) aporta una textura sedosa y notas de mazapán.',
  },
  {
    name: "Pendennis Club",
    category: "Difford's Classics",
    family: "Sour",
    glass: "Copa de Cóctel",
    method: "Agitado y colado",
    garnish: "Twist de lima",
    color: "#E8C880",
    icon: "🏛️",
    ingredients: ["60ml Ginebra", "30ml Brandy de albaricoque", "22ml Zumo de lima", "2 dashes Peychaud's"],
    story: 'Originado en el Pendennis Club de Louisville, Kentucky. Se rumorea que este club también vio nacer el Old Fashioned.',
  },

  // ═══ SPIRIT-FORWARD / STIRRED FAMILY (10) ═════════════════

  {
    name: "Rob Roy",
    category: "Difford's Classics",
    family: "Stirred",
    glass: "Copa de Cóctel",
    method: "Removido",
    garnish: "Cereza al marrasquino",
    color: "#8B2500",
    icon: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    ingredients: ["60ml Scotch Whisky", "30ml Vermut rojo dulce", "2 dashes Angostura"],
    story: 'El Manhattan escocés, creado en 1894 en el Waldorf de Nueva York para el estreno de la ópera Rob Roy.',
  },
  {
    name: "Bijou",
    category: "Difford's Classics",
    family: "Stirred",
    glass: "Copa de Cóctel",
    method: "Removido",
    garnish: "Cereza al marrasquino y twist de limón",
    color: "#8B6914",
    icon: "💎",
    ingredients: ["30ml Ginebra", "30ml Chartreuse Verde", "30ml Vermut rojo dulce", "1 dash Angostura"],
    story: 'Joya de 1890, cada ingrediente representa una gema: ginebra (diamante), chartreuse (esmeralda), vermut (rubí).',
  },
  {
    name: "Toronto",
    category: "Difford's Classics",
    family: "Stirred",
    glass: "Copa de Cóctel",
    method: "Removido",
    garnish: "Twist de naranja",
    color: "#A0522D",
    icon: "🍁",
    ingredients: ["60ml Whiskey canadiense", "7ml Fernet Branca", "7ml Jarabe simple", "2 dashes Angostura"],
    story: 'Old Fashioned canadiense con un toque de Fernet Branca. Su amargor herbáceo da complejidad inesperada al whisky dulce.',
  },
  {
    name: "Black Manhattan",
    category: "Difford's Classics",
    family: "Stirred",
    glass: "Copa de Cóctel",
    method: "Removido",
    garnish: "Cereza Luxardo",
    color: "#2F1B14",
    icon: "🌑",
    ingredients: ["60ml Whiskey de centeno", "30ml Amaro Averna", "2 dashes Angostura", "1 dash Orange bitters"],
    story: 'Variación oscura del Manhattan por Todd Smith. Sustituye el vermut por Amaro Averna, creando un perfil más profundo y amargo.',
  },
  {
    name: "Blood and Sand",
    category: "Difford's Classics",
    family: "Stirred",
    glass: "Copa de Cóctel",
    method: "Agitado y colado",
    garnish: "Twist de naranja flambeado",
    color: "#B22222",
    icon: "🩸",
    ingredients: ["22ml Scotch Whisky", "22ml Vermut rojo dulce", "22ml Cherry Heering", "22ml Zumo de naranja"],
    story: 'Nombrado por la película de Rodolfo Valentino (1922). Uno de los pocos cócteles clásicos con Scotch que incluye zumo de fruta.',
  },
  {
    name: "Bobby Burns",
    category: "Difford's Classics",
    family: "Stirred",
    glass: "Copa de Cóctel",
    method: "Removido",
    garnish: "Twist de limón",
    color: "#9B4D2B",
    icon: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    ingredients: ["45ml Scotch Whisky", "45ml Vermut rojo dulce", "7ml Bénédictine"],
    story: 'Homenaje al poeta nacional de Escocia. El toque de Bénédictine añade notas de miel y especias al Rob Roy clásico.',
  },
  {
    name: "Chrysanthemum",
    category: "Difford's Classics",
    family: "Stirred",
    glass: "Copa de Cóctel",
    method: "Removido",
    garnish: "Twist de naranja",
    color: "#C8A040",
    icon: "🌼",
    ingredients: ["60ml Vermut seco", "30ml Bénédictine", "1 barspoon Absenta"],
    story: 'Cóctel de bajo ABV con vermut seco como base. La absenta aporta un susurro anisado. Popular en el París de los años 20.',
  },
  {
    name: "Greenpoint",
    category: "Difford's Classics",
    family: "Stirred",
    glass: "Copa de Cóctel",
    method: "Removido",
    garnish: "Twist de limón",
    color: "#5C4033",
    icon: "🟢",
    ingredients: ["60ml Whiskey de centeno", "15ml Chartreuse Amarilla", "15ml Punt e Mes", "1 dash Angostura", "1 dash Orange bitters"],
    story: 'Creado por Michael McIlroy en Milk & Honey. Nombrado por el barrio de Brooklyn, es un Manhattan con toques herbáceos.',
  },
  {
    name: "Remember the Maine",
    category: "Difford's Classics",
    family: "Stirred",
    glass: "Copa de Cóctel",
    method: "Removido",
    garnish: "Cereza al marrasquino",
    color: "#A02020",
    icon: "⚓",
    ingredients: ["60ml Whiskey de centeno", "22ml Vermut rojo dulce", "7ml Cherry Heering", "1 barspoon Absenta"],
    story: 'Nombrado por el USS Maine, cuyo hundimiento provocó la Guerra Hispanoamericana. Combina whisky con cherry y un enjuague de absenta.',
  },
  {
    name: "Bamboo",
    category: "Difford's Classics",
    family: "Stirred",
    glass: "Copa de Cóctel",
    method: "Removido",
    garnish: "Twist de limón",
    color: "#C8B060",
    icon: "🎋",
    ingredients: ["45ml Jerez fino", "45ml Vermut seco", "1 dash Angostura", "1 dash Orange bitters"],
    story: 'Creado en el Grand Hotel de Yokohama en 1890. Un aperitivo elegante de bajo ABV que combina jerez y vermut seco.',
  },

  // ═══ TIKI / TROPICAL FAMILY (12) ══════════════════════════

  {
    name: "Jungle Bird",
    category: "Difford's Classics",
    family: "Tiki",
    glass: "Old Fashioned (Rocks)",
    method: "Agitado y colado",
    garnish: "Rodaja de piña",
    color: "#C03030",
    icon: "🦜",
    ingredients: ["45ml Ron oscuro", "22ml Campari", "45ml Zumo de piña", "15ml Zumo de lima", "15ml Jarabe simple"],
    story: 'Creado en 1978 en el Kuala Lumpur Hilton. Rompió moldes al introducir Campari en el mundo tiki, uniendo Italia y el trópico.',
  },
  {
    name: "Painkiller",
    category: "Difford's Classics",
    family: "Tiki",
    glass: "Vaso Highball",
    method: "Agitado y colado",
    garnish: "Nuez moscada rallada y rodaja de naranja",
    color: "#F0C070",
    icon: "💊",
    ingredients: ["60ml Ron Pusser's", "120ml Zumo de piña", "30ml Zumo de naranja", "30ml Crema de coco"],
    story: 'Originado en el Soggy Dollar Bar de las Islas Vírgenes. Los clientes nadaban hasta el bar y pagaban con dólares mojados.',
  },
  {
    name: "Navy Grog",
    category: "Difford's Classics",
    family: "Tiki",
    glass: "Old Fashioned (Rocks)",
    method: "Agitado y colado",
    garnish: "Ramita de menta",
    color: "#B08030",
    icon: "⚓",
    ingredients: ["22ml Ron blanco", "22ml Ron dorado", "22ml Ron Demerara", "22ml Zumo de lima", "22ml Zumo de pomelo", "15ml Jarabe de miel"],
    story: 'Don the Beachcomber creó esta versión refinada del grog naval. Tres rones distintos crean capas de complejidad.',
  },
  {
    name: "Three Dots and a Dash",
    category: "Difford's Classics",
    family: "Tiki",
    glass: "Vaso Highball",
    method: "Agitado y colado",
    garnish: "Cereza y piña en palillo",
    color: "#D4702B",
    icon: "✌️",
    ingredients: ["45ml Ron añejo", "15ml Zumo de lima", "15ml Zumo de naranja", "15ml Jarabe de miel", "7ml Falernum", "7ml Allspice Dram"],
    story: 'Creado por Don the Beachcomber durante la WWII. El nombre es código Morse para V (Victoria). Guarnición: 3 cerezas y 1 piña.',
  },
  {
    name: "Saturn",
    category: "Difford's Classics",
    family: "Tiki",
    glass: "Copa de Cóctel",
    method: "Agitado y colado",
    garnish: "Rodaja de limón",
    color: "#D4A860",
    icon: "🪐",
    ingredients: ["30ml Ginebra", "15ml Zumo de limón", "7ml Falernum", "7ml Orgeat", "7ml Maracuyá"],
    story: 'Creado por J. \"Popo\" Galsini, ganó la competición IBA en 1967. Combina ginebra con sabores tropicales de forma inesperada.',
  },
  {
    name: "Fog Cutter",
    category: "Difford's Classics",
    family: "Tiki",
    glass: "Copa Huracán",
    method: "Agitado y colado",
    garnish: "Ramita de menta",
    color: "#C8A050",
    icon: "🌫️",
    ingredients: ["30ml Ron blanco", "30ml Brandy", "15ml Ginebra", "60ml Zumo de naranja", "30ml Zumo de limón", "15ml Orgeat", "15ml Jerez amontillado (float)"],
    story: 'Trader Vic advirtió: \"Si tienes niebla, este la cortará.\" Con tres destilados base, es uno de los tragos tiki más potentes.',
  },
  {
    name: "Missionary's Downfall",
    category: "Difford's Classics",
    family: "Tiki",
    glass: "Vaso Highball",
    method: "Licuado",
    garnish: "Ramita de menta abundante",
    color: "#90C060",
    icon: "🌴",
    ingredients: ["45ml Ron blanco", "15ml Crème de Pêche", "30ml Zumo de lima", "15ml Jarabe de miel", "60g Piña fresca", "8 hojas de menta"],
    story: 'Don the Beachcomber diseñó este cóctel licuado con abundante menta y melocotón. Capaz de tentar hasta al misionero más devoto.',
  },
  {
    name: "Scorpion",
    category: "Difford's Classics",
    family: "Tiki",
    glass: "Copa Huracán",
    method: "Licuado",
    garnish: "Flor comestible y ramita de menta",
    color: "#E8A030",
    icon: "🦂",
    ingredients: ["60ml Ron blanco", "30ml Brandy", "15ml Orgeat", "45ml Zumo de naranja", "30ml Zumo de limón"],
    story: 'Bowl tiki clásico de Trader Vic, originalmente servido para compartir. El orgeat aporta notas de almendra al ponche tropical.',
  },
  {
    name: "Pearl Diver",
    category: "Difford's Classics",
    family: "Tiki",
    glass: "Vaso Highball",
    method: "Licuado",
    garnish: "Rodaja de lima",
    color: "#D4B870",
    icon: "🦪",
    ingredients: ["45ml Ron dorado", "22ml Zumo de lima", "15ml Zumo de naranja", "15ml Falernum", "30ml Mantequilla de Don's (Don's mix)"],
    story: 'Don the Beachcomber inventó la Pearl Diver con su mezcla secreta de mantequilla y especias. Textura sedosa y sabor exótico.',
  },
  {
    name: "Jet Pilot",
    category: "Difford's Classics",
    family: "Tiki",
    glass: "Old Fashioned (Rocks)",
    method: "Agitado y colado",
    garnish: "Twist de lima",
    color: "#A05020",
    icon: "✈️",
    ingredients: ["22ml Ron jamaicano", "22ml Ron Demerara", "22ml Ron 151 (overproof)", "15ml Zumo de lima", "15ml Zumo de pomelo", "7ml Falernum", "7ml Canela simple", "1 dash Angostura", "1 dash Absenta"],
    story: 'Trader Vic creó esta versión del Test Pilot de Don. Tres rones de alta potencia justifican el nombre: combustible de avión.',
  },
  {
    name: "Test Pilot",
    category: "Difford's Classics",
    family: "Tiki",
    glass: "Copa de Cóctel",
    method: "Agitado y colado",
    garnish: "Cereza y ramita de menta",
    color: "#B86030",
    icon: "🧪",
    ingredients: ["45ml Ron oscuro", "15ml Ron blanco", "15ml Zumo de lima", "7ml Falernum", "7ml Cointreau", "1 dash Angostura"],
    story: 'Don the Beachcomber lo llamó así porque necesitas ser un piloto experimentado para probar este brebaje tropical potente.',
  },
  {
    name: "Corn 'n' Oil",
    category: "Difford's Classics",
    family: "Tiki",
    glass: "Old Fashioned (Rocks)",
    method: "Construido",
    garnish: "Cuña de lima",
    color: "#4A2810",
    icon: "🏝️",
    ingredients: ["60ml Ron Blackstrap", "22ml Falernum", "15ml Zumo de lima", "2 dashes Angostura"],
    story: 'Cóctel de Barbados con ron blackstrap y falernum. Su nombre describe la apariencia oscura y oleosa del trago.',
  },

  // ═══ ADVANCED / MIXED FAMILY (10) ═════════════════════════

  {
    name: "Sherry Cobbler",
    category: "Difford's Classics",
    family: "Mixed",
    glass: "Copa de Vino",
    method: "Construido",
    garnish: "Frutas de temporada y ramita de menta",
    color: "#A06030",
    icon: "🍇",
    ingredients: ["90ml Jerez amontillado", "15ml Jarabe simple", "2 rodajas de naranja"],
    story: 'El cóctel que popularizó la pajita en el siglo XIX. Un cobbler se define por servirse sobre hielo picado con fruta fresca.',
  },
  {
    name: "Pisco Punch",
    category: "Difford's Classics",
    family: "Mixed",
    glass: "Copa de Cóctel",
    method: "Agitado y colado",
    garnish: "Rodaja de piña",
    color: "#D4A040",
    icon: "🥊",
    ingredients: ["60ml Pisco", "22ml Zumo de limón", "22ml Zumo de piña", "15ml Jarabe de goma arábiga", "7ml Cointreau"],
    story: 'Receta legendaria del Bank Exchange en San Francisco (1850s). La receta original se perdió con la Prohibición y fue recreada.',
  },
  {
    name: "Chartreuse Swizzle",
    category: "Difford's Classics",
    family: "Mixed",
    glass: "Vaso Highball",
    method: "Construido",
    garnish: "Nuez moscada rallada y ramita de menta",
    color: "#7CB342",
    icon: "🌿",
    ingredients: ["45ml Chartreuse Verde", "22ml Zumo de piña", "15ml Zumo de lima", "15ml Falernum"],
    story: 'Marco Dionysos fusionó el mundo tiki con el herbal francés. Se prepara con la técnica del swizzle: paleta girada entre las palmas.',
  },
  {
    name: "Corpse Reviver #1",
    category: "Difford's Classics",
    family: "Mixed",
    glass: "Copa de Cóctel",
    method: "Removido",
    garnish: "Sin decoración",
    color: "#9B6930",
    icon: "💀",
    ingredients: ["30ml Cognac", "15ml Calvados", "15ml Vermut rojo dulce"],
    story: 'Harry Craddock incluyó dos Corpse Revivers en su Savoy Cocktail Book. El #1, a base de brandy y removido, es más suave que su hermano.',
  },
  {
    name: "Death in the Afternoon",
    category: "Difford's Classics",
    family: "Mixed",
    glass: "Flauta de Champán",
    method: "Construido",
    garnish: "Sin decoración",
    color: "#C8D8A0",
    icon: "📖",
    ingredients: ["30ml Absenta", "120ml Champán frío"],
    story: 'Ernest Hemingway inventó este cóctel y lo describió así: \"Verter la absenta, añadir champán hasta que tome un bonito color opalescente.\"',
  },
  {
    name: "Japanese Slipper",
    category: "Difford's Classics",
    family: "Mixed",
    glass: "Copa de Cóctel",
    method: "Agitado y colado",
    garnish: "Rodaja de limón",
    color: "#50C050",
    icon: "🎌",
    ingredients: ["30ml Midori", "30ml Cointreau", "30ml Zumo de limón"],
    story: 'Creado en Melbourne en 1984 por Jean-Paul Bourguignon. Partes iguales crean un cóctel verde vibrante, dulce y cítrico.',
  },
  {
    name: "Improved Whiskey Cocktail",
    category: "Difford's Classics",
    family: "Mixed",
    glass: "Old Fashioned (Rocks)",
    method: "Removido",
    garnish: "Twist de limón y cereza",
    color: "#A06030",
    icon: "📜",
    ingredients: ["60ml Whiskey de centeno", "7ml Marrasquino", "7ml Absenta", "2 dashes Angostura", "1 barspoon Jarabe simple"],
    story: 'Versión \"mejorada\" del Old Fashioned, añade marrasquino y un enjuague de absenta. Puente entre la coctelería clásica y moderna.',
  },
  {
    name: "Milk Punch",
    category: "Difford's Classics",
    family: "Mixed",
    glass: "Old Fashioned (Rocks)",
    method: "Agitado y colado",
    garnish: "Nuez moscada rallada",
    color: "#F0E8D0",
    icon: "🥛",
    ingredients: ["60ml Bourbon", "90ml Leche entera", "15ml Jarabe simple", "5ml Extracto de vainilla"],
    story: 'Trago matutino del sur de EE.UU. La leche y vainilla suavizan el bourbon. En Nueva Orleans es tradición de Mardi Gras.',
  },
  {
    name: "Lion's Tail",
    category: "Difford's Classics",
    family: "Mixed",
    glass: "Copa de Cóctel",
    method: "Agitado y colado",
    garnish: "Twist de limón",
    color: "#C89030",
    icon: "🦁",
    ingredients: ["60ml Bourbon", "22ml Zumo de lima", "15ml Allspice Dram", "7ml Jarabe simple", "2 dashes Angostura"],
    story: 'Publicado en Café Royal Cocktail Book (1937). El Allspice Dram (pimento dram) le da un aroma especiado caribreño único.',
  },
  {
    name: "Chicago Fizz",
    category: "Difford's Classics",
    family: "Mixed",
    glass: "Vaso Highball",
    method: "Dry shake y agitado",
    garnish: "Sin decoración",
    color: "#C0607B",
    icon: "🌆",
    ingredients: ["30ml Ron oscuro", "30ml Oporto Ruby", "15ml Zumo de limón", "15ml Jarabe simple", "15ml Clara de huevo", "Soda"],
    story: 'Fizz sofisticado que combina ron con Oporto. La clara de huevo aporta espuma sedosa, coronada con soda efervescente.',
  },
];
