export const IBA_CONTEMPORARY = [
  {
    name: "Bellini",
    category: "Contemporary Classics",
    glass: "Flauta de Champán",
    method: "Removido suavemente",
    garnish: "Sin decoración",
    color: "#FADADD",
    icon: "🍑",
    ingredients: ["100ml Prosecco","50ml Puré de Melocotón Blanco"],
    story: 'Creado por Giuseppe Cipriani en el Harry\'s Bar de Venecia en 1948. Nombrado por el pintor renacentista Giovanni Bellini.',
  },
  {
    name: "Black Russian",
    category: "Contemporary Classics",
    glass: "Old Fashioned (Rocks)",
    method: "Construido y removido",
    garnish: "Sin decoración",
    color: "#1A0A00",
    icon: "🖤",
    ingredients: ["50ml Vodka","20ml Licor de Café"],
    story: 'Creado en 1949 por Gustave Tops en el Hotel Metropole de Bruselas. Dedicado a la embajadora de EE.UU. Perle Mesta.',
  },
  {
    name: "Bloody Mary",
    category: "Contemporary Classics",
    glass: "Vaso Highball",
    method: "Removido",
    garnish: "Apio y rodaja de limón",
    color: "#C0392B",
    icon: "🍅",
    ingredients: ["45ml Vodka","90ml Zumo de Tomate","15ml Zumo de Limón","Salsa Worcestershire","Tabasco","Sal de Apio","Pimienta"],
    story: 'Creado ca. 1921 por Fernand Petiot en el Harry\'s New York Bar de París. El "remedio para la resaca" más famoso del mundo.',
  },
  {
    name: "Caipirinha",
    category: "Contemporary Classics",
    glass: "Old Fashioned (Rocks)",
    method: "Macerado y construido",
    garnish: "Sin decoración",
    color: "#8FBC8F",
    icon: "🇧🇷",
    ingredients: ["60ml Cachaça","1 Lima cortada","4 cucharaditas de Azúcar"],
    story: 'El cóctel nacional de Brasil. La cachaça, destilado de caña de azúcar, le da un carácter único y terroso.',
  },
  {
    name: "Champagne Cocktail",
    category: "Contemporary Classics",
    glass: "Flauta de Champán",
    method: "Construido",
    garnish: "Piel de naranja y cereza",
    color: "#F9E79F",
    icon: "🍾",
    ingredients: ["90ml Champán","10ml Cognac","1 terrón de azúcar con Angostura"],
    story: 'Aparece en el libro de Jerry Thomas (1862). El terrón de azúcar con bitters crea un espectáculo de burbujas continuas.',
  },
  {
    name: "Corpse Reviver #2",
    category: "Contemporary Classics",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Piel de naranja",
    color: "#E8DAC0",
    icon: "💀",
    ingredients: ["30ml Ginebra","30ml Cointreau","30ml Lillet Blanc","30ml Zumo de Limón","1 dash Absenta"],
    story: 'Del libro "The Savoy Cocktail Book" (1930). Harry Craddock advirtió: "Toma cuatro y también serás revivido de entre los muertos".',
  },
  {
    name: "Cosmopolitan",
    category: "Contemporary Classics",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Twist de limón",
    color: "#E74C3C",
    icon: "🌸",
    ingredients: ["40ml Vodka Citron","15ml Cointreau","15ml Zumo de Lima","30ml Zumo de Arándano"],
    story: 'Popularizado en los 90s por "Sex and the City". Creado ca. 1987-1988 por Cheryl Cook o Toby Cecchini.',
  },
  {
    name: "Cuba Libre",
    category: "Contemporary Classics",
    glass: "Vaso Highball",
    method: "Construido",
    garnish: "Cuña de lima",
    color: "#3D1C02",
    icon: "🇨🇺",
    ingredients: ["50ml Ron Blanco","120ml Cola","10ml Zumo de Lima"],
    story: 'Nacido en La Habana ca. 1900 tras la independencia cubana. El grito "¡Por Cuba libre!" se convirtió en su nombre.',
  },
  {
    name: "French 75",
    category: "Contemporary Classics",
    glass: "Flauta de Champán",
    method: "Agitado y completado con champán",
    garnish: "Sin decoración",
    color: "#ABEBC6",
    icon: "🫧",
    ingredients: ["30ml Ginebra","15ml Zumo de Limón","15ml Jarabe de Azúcar","60ml Champán"],
    story: 'Creado en el New York Bar de París durante la Primera Guerra Mundial. Su nombre viene del cañón francés de 75mm por su "patada".',
  },
  {
    name: "French Connection",
    category: "Contemporary Classics",
    glass: "Old Fashioned (Rocks)",
    method: "Construido y removido",
    garnish: "Sin decoración",
    color: "#A0522D",
    icon: "🇫🇷",
    ingredients: ["35ml Cognac","35ml Amaretto"],
    story: 'Sencillo y elegante, combina dos licores de tradición europea. Su nombre evoca la ruta del narcotráfico franco-americana de los 70s.',
  },
  {
    name: "Golden Dream",
    category: "Contemporary Classics",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Sin decoración",
    color: "#FFD700",
    icon: "✨",
    ingredients: ["20ml Galliano","20ml Triple Sec","20ml Zumo de Naranja","20ml Crema Fresca"],
    story: 'Un sueño dorado y cremoso, creado en los años 60. El Galliano le da su color y toque de vainilla.',
  },
  {
    name: "Grasshopper",
    category: "Contemporary Classics",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Sin decoración",
    color: "#3CB371",
    icon: "🦗",
    ingredients: ["20ml Crème de Cacao Blanco","20ml Crème de Menthe Verde","20ml Crema Fresca"],
    story: 'Cóctel postre de color verde brillante, creado en el Tujague\'s de Nueva Orleans. Popular en los años 50-60 como digestivo.',
  },
  {
    name: "Hemingway Special",
    category: "Contemporary Classics",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Rodaja de lima",
    color: "#FFB6C1",
    icon: "📖",
    ingredients: ["60ml Ron Blanco","40ml Zumo de Pomelo","15ml Marrasquino","15ml Zumo de Lima"],
    story: 'Creado para Ernest Hemingway en el bar El Floridita de La Habana. El escritor pedía el doble de ron y sin azúcar.',
  },
  {
    name: "Horse's Neck",
    category: "Contemporary Classics",
    glass: "Vaso Highball",
    method: "Construido",
    garnish: "Espiral larga de limón",
    color: "#CDB79E",
    icon: "🐴",
    ingredients: ["40ml Cognac","120ml Ginger Ale","1 dash Angostura (opcional)"],
    story: 'Originalmente sin alcohol, se le añadió brandy a finales del siglo XIX. La larga espiral de limón simula el cuello de un caballo.',
  },
  {
    name: "Irish Coffee",
    category: "Contemporary Classics",
    glass: "Copa de Irish Coffee",
    method: "Construido",
    garnish: "Sin decoración",
    color: "#3E2723",
    icon: "☕",
    ingredients: ["50ml Whiskey Irlandés","120ml Café Caliente","50ml Crema Batida","1 cucharadita de Azúcar"],
    story: 'Creado por Joe Sheridan en el aeropuerto de Foynes, Irlanda, en los años 40 para calentar a los viajeros transatlánticos.',
  },
  {
    name: "Kir",
    category: "Contemporary Classics",
    glass: "Copa de Vino",
    method: "Construido",
    garnish: "Sin decoración",
    color: "#8B0045",
    icon: "🍷",
    ingredients: ["90ml Vino Blanco Seco","10ml Crème de Cassis"],
    story: 'Nombrado por Félix Kir, alcalde de Dijon, que lo servía en recepciones oficiales. Con champán se convierte en "Kir Royal".',
  },
  {
    name: "Long Island Iced Tea",
    category: "Contemporary Classics",
    glass: "Vaso Highball",
    method: "Construido",
    garnish: "Rodaja de limón",
    color: "#DAA06D",
    icon: "🏖️",
    ingredients: ["15ml Vodka","15ml Ginebra","15ml Ron Blanco","15ml Tequila","15ml Triple Sec","30ml Zumo de Limón","20ml Jarabe","Cola"],
    story: 'A pesar de no llevar té, su color lo simula. Creado en los años 70 en Long Island. Famoso por su alto contenido alcohólico disimulado.',
  },
  {
    name: "Mai Tai",
    category: "Contemporary Classics",
    glass: "Old Fashioned (Rocks)",
    method: "Agitado",
    garnish: "Piña y menta fresca",
    color: "#D2691E",
    icon: "🌺",
    ingredients: ["30ml Ron Jamaicano Ámbar","30ml Rhum Martinica","15ml Curaçao de Naranja","15ml Orgeat (Jarabe de Almendra)","30ml Zumo de Lima","7.5ml Jarabe"],
    story: 'Creado por Trader Vic en 1944. Cuando una amiga tahitiana lo probó exclamó "Maita\'i roa ae!" (¡Muy bueno!).',
  },
  {
    name: "Margarita",
    category: "Contemporary Classics",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Rodaja de lima y borde de sal (opcional)",
    color: "#27AE60",
    icon: "🌵",
    ingredients: ["50ml Tequila","20ml Triple Sec","15ml Zumo de Lima"],
    story: 'Uno de los cócteles más pedidos del mundo. Su origen exacto es disputado entre varios bartenders de los años 40-50.',
  },
  {
    name: "Mimosa",
    category: "Contemporary Classics",
    glass: "Flauta de Champán",
    method: "Construido",
    garnish: "Sin decoración",
    color: "#FFCC33",
    icon: "🌼",
    ingredients: ["75ml Zumo de Naranja","75ml Prosecco"],
    story: 'Creado en el Hotel Ritz de París en 1925. Nombrado por la flor de la mimosa, por su color amarillo brillante. El clásico del brunch.',
  },
  {
    name: "Mint Julep",
    category: "Contemporary Classics",
    glass: "Copa Julep (Julep Cup)",
    method: "Macerado y construido",
    garnish: "Ramo de menta fresca",
    color: "#2E8B57",
    icon: "🌿",
    ingredients: ["60ml Bourbon","4 ramitas de Menta","1 cucharadita de Azúcar","Agua"],
    story: 'El cóctel oficial del Kentucky Derby desde 1938. Se sirve en copa de plata o peltre para mantener el frío.',
  },
  {
    name: "Mojito",
    category: "Contemporary Classics",
    glass: "Vaso Highball",
    method: "Macerado y construido",
    garnish: "Menta fresca y rodaja de lima",
    color: "#16A085",
    icon: "🌿",
    ingredients: ["45ml Ron Blanco","20ml Zumo de Lima","Hojas de Menta","2 cucharaditas de Azúcar","Soda"],
    story: 'El cóctel cubano por excelencia. Se dice que ya se bebía en La Habana en el siglo XVI, aunque con aguardiente.',
  },
  {
    name: "Moscow Mule",
    category: "Contemporary Classics",
    glass: "Taza de Cobre",
    method: "Construido",
    garnish: "Rodaja de lima",
    color: "#BDB76B",
    icon: "🫚",
    ingredients: ["45ml Vodka","120ml Ginger Beer","10ml Zumo de Lima"],
    story: 'Creado en 1941 en el Cock \'n\' Bull de Hollywood para vender vodka Smirnoff. La taza de cobre es parte de su leyenda.',
  },
  {
    name: "Piña Colada",
    category: "Contemporary Classics",
    glass: "Copa Huracán",
    method: "Licuado",
    garnish: "Piña y cereza",
    color: "#F7DC6F",
    icon: "🍍",
    ingredients: ["50ml Ron Blanco","30ml Crema de Coco","50ml Zumo de Piña"],
    story: 'Cóctel nacional de Puerto Rico. Creado en el Caribe Hilton de San Juan en 1954 por Ramón "Monchito" Marrero.',
  },
  {
    name: "Pisco Sour",
    category: "Contemporary Classics",
    glass: "Copa Sour / Coupe",
    method: "Agitado",
    garnish: "Gotas de bitters en la espuma",
    color: "#F0E68C",
    icon: "🇵🇪",
    ingredients: ["60ml Pisco","30ml Zumo de Limón","20ml Jarabe Simple","Clara de Huevo","Bitters Angostura (decoración)"],
    story: 'Cóctel bandera de Perú (y Chile lo disputa). Creado por Victor Morris en Lima en los años 20. La espuma de clara es esencial.',
  },
  {
    name: "Sea Breeze",
    category: "Contemporary Classics",
    glass: "Vaso Highball",
    method: "Construido",
    garnish: "Piel de naranja y cereza",
    color: "#DC3545",
    icon: "🌊",
    ingredients: ["40ml Vodka","120ml Zumo de Arándano","30ml Zumo de Pomelo"],
    story: 'Cóctel refrescante de los años 80 popularizado por la marca Ocean Spray. Su nombre evoca la brisa marina.',
  },
  {
    name: "Sex on the Beach",
    category: "Contemporary Classics",
    glass: "Vaso Highball",
    method: "Construido",
    garnish: "Rodaja de naranja",
    color: "#FF6347",
    icon: "🏝️",
    ingredients: ["40ml Vodka","20ml Licor de Melocotón (Peach Schnapps)","40ml Zumo de Naranja","40ml Zumo de Arándano"],
    story: 'Creado en los años 80 en Florida durante un concurso de coctelería. Su nombre provocador lo hizo inmediatamente popular.',
  },
  {
    name: "Singapore Sling",
    category: "Contemporary Classics",
    glass: "Copa Huracán",
    method: "Agitado",
    garnish: "Piña y cereza",
    color: "#E74C3C",
    icon: "🌺",
    ingredients: ["30ml Ginebra","15ml Cherry Heering","7.5ml Cointreau","7.5ml Bénédictine","120ml Zumo de Piña","15ml Zumo de Lima","10ml Granadina","Angostura Bitters"],
    story: 'Creado ca. 1915 por Ngiam Tong Boon en el Raffles Hotel de Singapur. Receta original perdida y reconstruida.',
  },
  {
    name: "Tequila Sunrise",
    category: "Contemporary Classics",
    glass: "Vaso Highball",
    method: "Construido con granadina flotada",
    garnish: "Rodaja de naranja",
    color: "#FF4500",
    icon: "🌅",
    ingredients: ["45ml Tequila","90ml Zumo de Naranja","15ml Granadina"],
    story: 'Popularizado por los Rolling Stones en su gira de 1972. El efecto degradado de colores simula un amanecer.',
  },
  {
    name: "Vesper",
    category: "Contemporary Classics",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Piel de limón",
    color: "#D5D5C0",
    icon: "🕵️",
    ingredients: ["45ml Ginebra","15ml Vodka","7.5ml Lillet Blanc"],
    story: 'Creado por Ian Fleming para James Bond en "Casino Royale" (1953). Nombrado por Vesper Lynd, la chica Bond.',
  },
  {
    name: "Zombie",
    category: "Contemporary Classics",
    glass: "Vaso Tumbler Alto",
    method: "Licuado",
    garnish: "Ramita de menta",
    color: "#8B0000",
    icon: "🧟",
    ingredients: ["45ml Ron Jamaicano Oscuro","45ml Ron Dorado Puertorriqueño","30ml Ron Demerara","20ml Zumo de Lima","15ml Falernum","15ml Don's Mix","1 cucharadita Granadina","Angostura Bitters","Pernod"],
    story: 'Creado por Donn Beach en los años 30. Era tan fuerte que limitaba a dos por persona. Su receta fue secreta durante décadas.',
  },
];
