export const IBA_UNFORGETTABLES = [
  {
    name: "Alexander",
    category: "The Unforgettables",
    glass: "Copa de Cóctel",
    method: "Agitado y colado",
    garnish: "Nuez moscada rallada",
    color: "#8B6914",
    icon: "🍫",
    ingredients: ["30ml Cognac","30ml Crème de Cacao Marrón","30ml Crema fresca"],
    story: 'Cóctel cremoso y elegante del siglo XIX. Originalmente hecho con ginebra, la versión con cognac se convirtió en la más popular.',
  },
  {
    name: "Americano",
    category: "The Unforgettables",
    glass: "Old Fashioned (Rocks)",
    method: "Construido",
    garnish: "Rodaja o piel de naranja",
    color: "#B5342D",
    icon: "🇮🇹",
    ingredients: ["30ml Campari","30ml Vermut Rojo Dulce","Splash de Soda"],
    story: 'Precursor del Negroni, creado en el Bar Gaspare Campari de Milán en los años 1860. Su nombre honra a los turistas americanos que lo adoraban.',
  },
  {
    name: "Angel Face",
    category: "The Unforgettables",
    glass: "Copa de Cóctel",
    method: "Agitado y colado",
    garnish: "Sin decoración",
    color: "#E8A952",
    icon: "😇",
    ingredients: ["30ml Ginebra","30ml Brandy de Albaricoque","30ml Calvados"],
    story: 'Cóctel de los años 20 con proporciones iguales. Su nombre sugiere que su sabor afrutado esconde una graduación alcohólica considerable.',
  },
  {
    name: "Aviation",
    category: "The Unforgettables",
    glass: "Copa de Cóctel",
    method: "Agitado y colado",
    garnish: "Cereza al marrasquino",
    color: "#9B8EC4",
    icon: "✈️",
    ingredients: ["45ml Ginebra","15ml Marrasquino","15ml Zumo de Limón","1 barspoon Crème de Violette"],
    story: 'Creado ca. 1916, su color lila evoca el cielo. La Crème de Violette le da ese tono etéreo que recuerda a las alturas.',
  },
  {
    name: "Between the Sheets",
    category: "The Unforgettables",
    glass: "Copa de Cóctel",
    method: "Agitado y colado",
    garnish: "Sin decoración",
    color: "#D4A84B",
    icon: "🛏️",
    ingredients: ["30ml Ron Blanco","30ml Cognac","30ml Triple Sec","20ml Zumo de Limón"],
    story: 'Variación del Sidecar creada en el Harry\'s New York Bar de París en los años 30. Su nombre provocador es parte de su encanto.',
  },
  {
    name: "Boulevardier",
    category: "The Unforgettables",
    glass: "Copa de Cóctel",
    method: "Removido",
    garnish: "Piel de naranja",
    color: "#9E2A2B",
    icon: "🎩",
    ingredients: ["45ml Bourbon o Rye Whiskey","30ml Campari","30ml Vermut Rojo Dulce"],
    story: 'Creado en los años 20 por Erskine Gwynne en París. Es esencialmente un Negroni con whiskey en lugar de ginebra.',
  },
  {
    name: "Brandy Crusta",
    category: "The Unforgettables",
    glass: "Copa de Cóctel",
    method: "Removido",
    garnish: "Borde de azúcar y piel de limón",
    color: "#C4863A",
    icon: "🍋",
    ingredients: ["50.5ml Brandy","7.5ml Marrasquino","1 barspoon Curaçao","15ml Zumo de Limón","1 barspoon Jarabe Simple","2 dash Bitters Aromáticos"],
    story: 'Creado por Joseph Santini en Nueva Orleans ca. 1850. La "crusta" de azúcar en el borde del vaso le da su nombre distintivo.',
  },
  {
    name: "Casino",
    category: "The Unforgettables",
    glass: "Old Fashioned (Rocks)",
    method: "Agitado",
    garnish: "Cereza y piel de limón",
    color: "#D4C685",
    icon: "🎰",
    ingredients: ["40ml Old Tom Gin","10ml Marrasquino","10ml Zumo de Limón","2 dash Orange Bitters"],
    story: 'Cóctel clásico que aparece en los libros de coctelería de principios del siglo XX. Su nombre evoca la elegancia de los casinos europeos.',
  },
  {
    name: "Clover Club",
    category: "The Unforgettables",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Frambuesa fresca",
    color: "#E8708A",
    icon: "🍓",
    ingredients: ["45ml Ginebra","15ml Jarabe de Frambuesa","15ml Zumo de Limón","Clara de huevo"],
    story: 'Originario del club Bellevue-Stratford de Filadelfia, anterior a la Prohibición. Su espuma rosada lo convierte en un clásico elegante.',
  },
  {
    name: "Daiquiri",
    category: "The Unforgettables",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Rodaja de lima",
    color: "#F5E6CA",
    icon: "🍹",
    ingredients: ["60ml Ron Blanco","20ml Zumo de Lima","2 barspoons Azúcar"],
    story: 'Nacido en las minas de Daiquirí, Cuba, en 1898. Su perfección reside en el equilibrio entre ron, ácido y dulce.',
  },
  {
    name: "Dry Martini",
    category: "The Unforgettables",
    glass: "Copa de Cóctel",
    method: "Removido",
    garnish: "Piel de limón o aceituna",
    color: "#D5E8D4",
    icon: "🫒",
    ingredients: ["60ml Ginebra","10ml Vermut Seco"],
    story: 'El rey de los cócteles. La proporción gin/vermut ha variado con cada era: de 2:1 en los 20s a casi solo ginebra hoy.',
  },
  {
    name: "Gin Fizz",
    category: "The Unforgettables",
    glass: "Vaso Highball",
    method: "Agitado y completado con soda",
    garnish: "Rodaja de limón",
    color: "#E8F0D8",
    icon: "🫧",
    ingredients: ["45ml Ginebra","30ml Zumo de Limón","10ml Jarabe Simple","Soda"],
    story: 'Cóctel efervescente popular desde mediados del siglo XIX. El "fizz" hace referencia al sonido de la carbonatación al servirse.',
  },
  {
    name: "Hanky Panky",
    category: "The Unforgettables",
    glass: "Copa de Cóctel",
    method: "Removido",
    garnish: "Piel de naranja",
    color: "#7B3F3F",
    icon: "🃏",
    ingredients: ["45ml London Dry Gin","45ml Vermut Rojo Dulce","7.5ml Fernet Branca"],
    story: 'Creado por Ada Coleman, bartender del Savoy Hotel de Londres, ca. 1903. Una de las primeras bartenders famosas de la historia.',
  },
  {
    name: "John Collins",
    category: "The Unforgettables",
    glass: "Vaso Highball",
    method: "Construido",
    garnish: "Cereza y rodaja de limón",
    color: "#F5EDCB",
    icon: "🍋",
    ingredients: ["45ml Ginebra (Old Tom)","30ml Zumo de Limón","15ml Jarabe Simple","60ml Soda"],
    story: 'Nombrado por un camarero del Limmer\'s Hotel de Londres en el siglo XIX. Es la base de la familia de cócteles "Collins".',
  },
  {
    name: "Last Word",
    category: "The Unforgettables",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Rodaja de lima",
    color: "#7CB342",
    icon: "🌿",
    ingredients: ["22.5ml Ginebra","22.5ml Chartreuse Verde","22.5ml Marrasquino","22.5ml Zumo de Lima"],
    story: 'Creado durante la Prohibición en el Detroit Athletic Club. Redescubierto en 2004 por Murray Stenson en Seattle.',
  },
  {
    name: "Manhattan",
    category: "The Unforgettables",
    glass: "Copa de Cóctel",
    method: "Removido",
    garnish: "Cereza al marrasquino",
    color: "#8E44AD",
    icon: "🍒",
    ingredients: ["50ml Rye Whiskey","20ml Vermut Rojo Dulce","1 dash Angostura Bitters"],
    story: 'Creado en el Manhattan Club de Nueva York ca. 1880. Una de las bases de la coctelería clásica americana.',
  },
  {
    name: "Martinez",
    category: "The Unforgettables",
    glass: "Copa de Cóctel",
    method: "Removido",
    garnish: "Piel de limón",
    color: "#C49A3C",
    icon: "🥂",
    ingredients: ["45ml London Dry Gin","45ml Vermut Rojo Dulce","1 barspoon Marrasquino","2 dash Orange Bitters"],
    story: 'Considerado el ancestro del Dry Martini. Aparece en los libros de coctelería de finales del siglo XIX.',
  },
  {
    name: "Mary Pickford",
    category: "The Unforgettables",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Cereza al marrasquino",
    color: "#F0A0A0",
    icon: "🎬",
    ingredients: ["45ml Ron Blanco","45ml Zumo de Piña","7.5ml Marrasquino","5ml Granadina"],
    story: 'Dedicado a la estrella del cine mudo Mary Pickford durante su visita a Cuba en los años 20. Un homenaje tropical a Hollywood.',
  },
  {
    name: "Monkey Gland",
    category: "The Unforgettables",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Piel de naranja",
    color: "#E88735",
    icon: "🐒",
    ingredients: ["45ml Ginebra Seca","45ml Zumo de Naranja","1 cucharada Absenta","1 cucharada Granadina"],
    story: 'Creado por Harry MacElhone en el Harry\'s Bar de París en los años 20. Su nombre viene de un tratamiento médico experimental de la época.',
  },
  {
    name: "Negroni",
    category: "The Unforgettables",
    glass: "Old Fashioned (Rocks)",
    method: "Removido",
    garnish: "Rodaja de naranja",
    color: "#C0392B",
    icon: "🍊",
    ingredients: ["30ml Ginebra","30ml Campari","30ml Vermut Rojo Dulce"],
    story: 'Creado en Florencia en 1919. El Conde Negroni pidió que sustituyeran la soda de su Americano por ginebra.',
  },
  {
    name: "Old Fashioned",
    category: "The Unforgettables",
    glass: "Old Fashioned (Rocks)",
    method: "Macerado y removido",
    garnish: "Cereza y rodaja de naranja",
    color: "#D4680A",
    icon: "🥃",
    ingredients: ["45ml Bourbon o Rye Whiskey","1 terrón de azúcar","Angostura Bitters","Splash de agua"],
    story: 'El cóctel más antiguo conocido. La receta original era simplemente "espíritu, azúcar, agua y bitters".',
  },
  {
    name: "Paradise",
    category: "The Unforgettables",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Sin decoración",
    color: "#F4A460",
    icon: "🌴",
    ingredients: ["30ml Ginebra","20ml Brandy de Albaricoque","15ml Zumo de Naranja"],
    story: 'Cóctel afrutado de los años 20 que combina ginebra con brandy de albaricoque. Su nombre evoca un sabor paradisíaco.',
  },
  {
    name: "Planter's Punch",
    category: "The Unforgettables",
    glass: "Vaso Tumbler",
    method: "Construido",
    garnish: "Piel de naranja",
    color: "#CD6839",
    icon: "🏝️",
    ingredients: ["45ml Ron Jamaicano","15ml Zumo de Lima","30ml Zumo de Caña de Azúcar"],
    story: 'Cóctel colonial de las plantaciones del Caribe. Su receta sigue la regla: "uno de agrio, dos de dulce, tres de fuerte, cuatro de débil".',
  },
  {
    name: "Porto Flip",
    category: "The Unforgettables",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Nuez moscada rallada",
    color: "#722F37",
    icon: "🍷",
    ingredients: ["15ml Brandy","45ml Oporto Tinto","10ml Yema de Huevo"],
    story: 'Los "flips" eran cócteles calientes con cerveza del siglo XVII. La versión con oporto y huevo se convirtió en un clásico del siglo XIX.',
  },
  {
    name: "Ramos Fizz",
    category: "The Unforgettables",
    glass: "Vaso Highball",
    method: "Dry shake y agitado",
    garnish: "Sin decoración",
    color: "#FAFAF0",
    icon: "☁️",
    ingredients: ["45ml Ginebra","15ml Zumo de Lima","15ml Zumo de Limón","30ml Jarabe de Azúcar","60ml Crema","30ml Clara de Huevo","Agua de Azahar","Extracto de Vainilla","Soda"],
    story: 'Creado en 1888 por Henry C. Ramos en Nueva Orleans. Se necesitaban hasta 12 minutos de agitación para lograr su textura sedosa.',
  },
  {
    name: "Rusty Nail",
    category: "The Unforgettables",
    glass: "Old Fashioned (Rocks)",
    method: "Construido y removido",
    garnish: "Piel de limón",
    color: "#B8860B",
    icon: "🔩",
    ingredients: ["45ml Scotch Whisky","25ml Drambuie"],
    story: 'Popular en los años 60 entre la élite neoyorquina del Rat Pack. La combinación de whisky escocés y Drambuie es sencilla pero adictiva.',
  },
  {
    name: "Sazerac",
    category: "The Unforgettables",
    glass: "Old Fashioned (Rocks)",
    method: "Enjuague y removido",
    garnish: "Piel de limón",
    color: "#DAA520",
    icon: "⚜️",
    ingredients: ["50ml Cognac o Rye Whiskey","10ml Absenta","1 terrón de azúcar","4 dash Peychaud's Bitters"],
    story: 'Cóctel oficial de Nueva Orleans. Nació ca. 1850 en el Sazerac Coffee House con cognac Sazerac-de-Forge et Fils.',
  },
  {
    name: "Sidecar",
    category: "The Unforgettables",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Sin decoración",
    color: "#D4A017",
    icon: "🏍️",
    ingredients: ["50ml Cognac","20ml Triple Sec","20ml Zumo de Limón"],
    story: 'Creado en París ca. 1920s, probablemente en el Harry\'s Bar o el Ritz. Su nombre viene del sidecar de una moto.',
  },
  {
    name: "Stinger",
    category: "The Unforgettables",
    glass: "Copa de Cóctel",
    method: "Removido",
    garnish: "Menta fresca (opcional)",
    color: "#C8B88A",
    icon: "🐝",
    ingredients: ["50ml Cognac","20ml Crème de Menthe Blanco"],
    story: 'Cóctel digestivo favorito de la alta sociedad desde principios del siglo XX. Su "aguijón" mentolado lo hace perfecto como after-dinner.',
  },
  {
    name: "Tuxedo",
    category: "The Unforgettables",
    glass: "Copa de Cóctel",
    method: "Removido",
    garnish: "Piel de limón y cereza",
    color: "#C5C5A0",
    icon: "🤵",
    ingredients: ["30ml Old Tom Gin","30ml Vermut Seco","1/2 barspoon Marrasquino","1/4 barspoon Absenta","3 dash Orange Bitters"],
    story: 'Nombrado por el Tuxedo Club de Nueva York, un exclusivo club de caballeros. Elegante como su nombre sugiere.',
  },
  {
    name: "Vieux Carré",
    category: "The Unforgettables",
    glass: "Copa de Cóctel",
    method: "Removido",
    garnish: "Piel de naranja y cereza",
    color: "#8B4513",
    icon: "🎷",
    ingredients: ["30ml Rye Whiskey","30ml Cognac","30ml Vermut Dulce","1 barspoon Bénédictine","2 dash Peychaud's Bitters"],
    story: 'Creado en el Hotel Monteleone de Nueva Orleans en los años 30. "Vieux Carré" es el nombre francés del Barrio Francés.',
  },
  {
    name: "Whiskey Sour",
    category: "The Unforgettables",
    glass: "Old Fashioned (Rocks)",
    method: "Agitado",
    garnish: "Rodaja de naranja y cereza",
    color: "#E67E22",
    icon: "🥃",
    ingredients: ["45ml Bourbon","25ml Zumo de Limón","20ml Jarabe de Azúcar","20ml Clara de Huevo (opcional)"],
    story: 'Aparece en el libro de Jerry Thomas (1862). La clara de huevo para dar espuma es característica del estilo New York Sour.',
  },
  {
    name: "White Lady",
    category: "The Unforgettables",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Piel de limón",
    color: "#F5F5DC",
    icon: "👰",
    ingredients: ["40ml Ginebra","30ml Triple Sec","20ml Zumo de Limón"],
    story: 'Creado por Harry MacElhone en el Ciro\'s Club de Londres en 1919 y perfeccionado en el Harry\'s Bar de París en 1929.',
  },
];
