export const IBA_NEW_ERA = [
  {
    name: "Barracuda",
    category: "New Era Drinks",
    glass: "Copa de Cóctel",
    method: "Agitado y completado con prosecco",
    garnish: "Piña y cereza",
    color: "#FFD54F",
    icon: "🐟",
    ingredients: ["45ml Ron Dorado","15ml Galliano","60ml Zumo de Piña","1 dash Zumo de Lima","Prosecco al completar"],
    story: 'Cóctel tropical con un toque italiano del Galliano y burbujas de prosecco.',
  },
  {
    name: "Bee's Knees",
    category: "New Era Drinks",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Piel de limón o naranja",
    color: "#F0C040",
    icon: "🐝",
    ingredients: ["52.5ml Ginebra","2 cucharaditas Jarabe de Miel","22.5ml Zumo de Limón","22.5ml Zumo de Naranja"],
    story: 'Cóctel de la era de la Prohibición. La miel disimulaba la ginebra de mala calidad. "Bee\'s knees" era jerga de los años 20 para "lo mejor".',
  },
  {
    name: "Bramble",
    category: "New Era Drinks",
    glass: "Old Fashioned (Rocks)",
    method: "Agitado y flotado",
    garnish: "Rodaja de limón y moras",
    color: "#6B2D5B",
    icon: "🫐",
    ingredients: ["50ml Ginebra","25ml Zumo de Limón","12.5ml Jarabe de Azúcar","15ml Crème de Mûre"],
    story: 'Creado por Dick Bradsell en Londres en 1984. Inspirado en los recuerdos de recoger moras en su infancia en la Isla de Wight.',
  },
  {
    name: "Canchanchara",
    category: "New Era Drinks",
    glass: "Vaso Terracota / Rocks",
    method: "Construido",
    garnish: "Rodaja de lima",
    color: "#C7A252",
    icon: "🍯",
    ingredients: ["60ml Aguardiente Cubano","15ml Zumo de Lima","15ml Miel","50ml Agua"],
    story: 'Bebida cubana del siglo XIX, posiblemente precursora del Daiquirí. Los soldados mambises la bebían durante las guerras de independencia.',
  },
  {
    name: "Dark 'n' Stormy",
    category: "New Era Drinks",
    glass: "Vaso Highball",
    method: "Construido",
    garnish: "Rodaja de lima",
    color: "#4A2600",
    icon: "⛈️",
    ingredients: ["60ml Ron Gosling's Black Seal","100ml Ginger Beer"],
    story: 'Cóctel nacional de Bermuda. Gosling\'s tiene la marca registrada del nombre. Las "nubes oscuras" del ron flotan sobre la ginger beer.',
  },
  {
    name: "Espresso Martini",
    category: "New Era Drinks",
    glass: "Copa de Cóctel",
    method: "Agitado fuerte",
    garnish: "3 granos de café",
    color: "#2C1810",
    icon: "☕",
    ingredients: ["50ml Vodka","30ml Kahlúa","10ml Jarabe de Azúcar","1 Espresso recién hecho"],
    story: 'Creado por Dick Bradsell en 1983 en Londres. Una modelo le pidió algo que "la despertara y luego la tumbara".',
  },
  {
    name: "Fernandito",
    category: "New Era Drinks",
    glass: "Vaso Highball",
    method: "Construido con hielo",
    garnish: "Sin decoración",
    color: "#1A1A0A",
    icon: "🇦🇷",
    ingredients: ["50ml Fernet Branca","100ml Cola"],
    story: 'Versión argentina de Fernet con Cola, bebida nacional del país.',
  },
  {
    name: "French Martini",
    category: "New Era Drinks",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Aceite de piel de limón",
    color: "#C24B8E",
    icon: "🍸",
    ingredients: ["45ml Vodka","15ml Licor de Frambuesa (Chambord)","15ml Zumo de Piña"],
    story: 'Creado en los años 80 en Nueva York. La espuma rosa y su elegancia lo hicieron favorito de los bares de moda.',
  },
  {
    name: "Illegal",
    category: "New Era Drinks",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Sin decoración",
    color: "#A08040",
    icon: "🔥",
    ingredients: ["30ml Mezcal","15ml Ron Overproof Jamaicano","15ml Falernum","1 barspoon Marrasquino","22.5ml Zumo de Lima","15ml Jarabe Simple","Clara de Huevo (opcional)"],
    story: 'Cóctel moderno que combina mezcal ahumado con ron jamaicano. Su nombre evoca lo prohibido y rebelde.',
  },
  {
    name: "Lemon Drop",
    category: "New Era Drinks",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Borde de azúcar",
    color: "#FFF44F",
    icon: "🍬",
    ingredients: ["30ml Vodka","20ml Triple Sec","15ml Zumo de Limón"],
    story: 'Creado en los años 70 en San Francisco. Nombrado por el caramelo de limón, por su sabor agridulce y adictivo.',
  },
  {
    name: "Naked and Famous",
    category: "New Era Drinks",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Sin decoración",
    color: "#D4742F",
    icon: "🌟",
    ingredients: ["22.5ml Mezcal","22.5ml Chartreuse Amarillo","22.5ml Aperol","22.5ml Zumo de Lima"],
    story: 'Creado por Joaquín Simó en Death & Co. de Nueva York en 2011. Variación moderna del Last Word con mezcal.',
  },
  {
    name: "New York Sour",
    category: "New Era Drinks",
    glass: "Old Fashioned (Rocks)",
    method: "Agitado y flotado",
    garnish: "Piel de limón/naranja y cereza",
    color: "#9B1B30",
    icon: "🗽",
    ingredients: ["60ml Rye o Bourbon","22.5ml Jarabe de Azúcar","30ml Zumo de Limón","Clara de Huevo","15ml Vino Tinto (flotado)"],
    story: 'Un Whiskey Sour coronado con vino tinto flotante. El contraste visual de las dos capas lo hace espectacular.',
  },
  {
    name: "Old Cuban",
    category: "New Era Drinks",
    glass: "Copa de Cóctel",
    method: "Agitado y completado con champán",
    garnish: "Ramita de menta",
    color: "#D4B896",
    icon: "💃",
    ingredients: ["6-8 hojas de Menta","45ml Ron Añejo","22.5ml Zumo de Lima","30ml Jarabe de Azúcar","2 dash Angostura Bitters","60ml Champán"],
    story: 'Creado por Audrey Saunders del Pegu Club de Nueva York. Un mojito elevado con champán y bitters.',
  },
  {
    name: "Paloma",
    category: "New Era Drinks",
    glass: "Vaso Highball",
    method: "Construido",
    garnish: "Rodaja de lima",
    color: "#F5A9B8",
    icon: "🕊️",
    ingredients: ["50ml Tequila","5ml Zumo de Lima","Pizca de Sal","100ml Refresco de Pomelo Rosa"],
    story: 'El cóctel de tequila más popular en México, más que la Margarita. "Paloma" significa "paloma" en español. Sencillo y refrescante.',
  },
  {
    name: "Paper Plane",
    category: "New Era Drinks",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Sin decoración",
    color: "#E89040",
    icon: "✈️",
    ingredients: ["30ml Bourbon","30ml Amaro Nonino","30ml Aperol","30ml Zumo de Limón"],
    story: 'Creado por Sam Ross en 2007 en el Milk & Honey de Nueva York. Nombrado por la canción de M.I.A. Proporciones iguales perfectas.',
  },
  {
    name: "Penicillin",
    category: "New Era Drinks",
    glass: "Old Fashioned (Rocks)",
    method: "Macerado y agitado",
    garnish: "Jengibre confitado",
    color: "#C4A35A",
    icon: "💊",
    ingredients: ["60ml Scotch Blended","7.5ml Lagavulin 16","22.5ml Zumo de Limón","22.5ml Jarabe de Miel","Jengibre fresco"],
    story: 'Creado por Sam Ross en el Milk & Honey de Nueva York en 2005. El float de Lagavulin ahumado es su firma. Un clásico moderno.',
  },
  {
    name: "Russian Spring Punch",
    category: "New Era Drinks",
    glass: "Vaso Highball",
    method: "Agitado y completado con espumoso",
    garnish: "Moras y rodaja de limón",
    color: "#7B2D8B",
    icon: "🍇",
    ingredients: ["25ml Vodka","25ml Zumo de Limón","15ml Crème de Cassis","10ml Jarabe de Azúcar","Vino Espumoso"],
    story: 'Creado por Dick Bradsell en Londres en los años 80. Combina la frescura de un punch con la elegancia del champán.',
  },
  {
    name: "Southside",
    category: "New Era Drinks",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Ramita de menta",
    color: "#90EE90",
    icon: "🌿",
    ingredients: ["60ml Ginebra","30ml Zumo de Limón","15ml Jarabe Simple","5-6 hojas de Menta","Clara de Huevo (opcional)"],
    story: 'Originario del Southside Sportsmen\'s Club de Long Island. Es esencialmente un Mojito con ginebra en lugar de ron.',
  },
  {
    name: "Spicy Fifty",
    category: "New Era Drinks",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Chile rojo",
    color: "#FF2400",
    icon: "🌶️",
    ingredients: ["50ml Vodka de Vainilla","15ml Licor de Flor de Saúco","15ml Zumo de Lima","10ml Jarabe de Miel","Chile Rojo"],
    story: 'Creado por Salvatore Calabrese en Londres. La combinación de vainilla, flor de saúco y chile crea una experiencia de sabores contrastantes.',
  },
  {
    name: "Spritz",
    category: "New Era Drinks",
    glass: "Copa de Vino",
    method: "Construido",
    garnish: "Rodaja de naranja",
    color: "#E8670A",
    icon: "🍊",
    ingredients: ["90ml Prosecco","60ml Aperol","Splash de Soda"],
    story: 'Fenómeno global del siglo XXI. El Aperol se creó en Padua en 1919; el spritz es tradición del Véneto italiano. Receta 3-2-1.',
  },
  {
    name: "Suffering Bastard",
    category: "New Era Drinks",
    glass: "Vaso Collins",
    method: "Agitado y completado con ginger beer",
    garnish: "Menta y rodaja de naranja",
    color: "#B8860B",
    icon: "😵",
    ingredients: ["30ml Cognac","30ml Ginebra","15ml Zumo de Lima","2 dash Angostura Bitters","Ginger Beer"],
    story: 'Creado por Joe Scialom en el Shepheard\'s Hotel de El Cairo durante la Segunda Guerra Mundial como remedio para la resaca.',
  },
  {
    name: "Tipperary",
    category: "New Era Drinks",
    glass: "Copa de Cóctel",
    method: "Removido",
    garnish: "Rodaja de naranja",
    color: "#556B2F",
    icon: "🍀",
    ingredients: ["50ml Whiskey Irlandés","25ml Vermut Dulce","15ml Chartreuse Verde","2 dash Angostura Bitters"],
    story: 'Nombrado por el condado irlandés de Tipperary. El Chartreuse verde le da una complejidad herbal única a este cóctel de whiskey.',
  },
  {
    name: "Tommy's Margarita",
    category: "New Era Drinks",
    glass: "Old Fashioned (Rocks)",
    method: "Agitado",
    garnish: "Rodaja de lima",
    color: "#7EC850",
    icon: "🌵",
    ingredients: ["60ml Tequila Reposado","30ml Zumo de Lima","30ml Néctar de Agave"],
    story: 'Creado por Julio Bermejo en Tommy\'s Mexican Restaurant de San Francisco. Sustituyó el triple sec por agave, simplificando y mejorando el clásico.',
  },
  {
    name: "Trinidad Sour",
    category: "New Era Drinks",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Sin decoración",
    color: "#A52A2A",
    icon: "🇹🇹",
    ingredients: ["45ml Angostura Bitters","30ml Orgeat (Jarabe de Almendra)","22.5ml Zumo de Limón","15ml Rye Whiskey"],
    story: 'Creado por Giuseppe González. Revolucionario por usar bitters como ingrediente principal en lugar de como acento.',
  },
  {
    name: "Ve.N.To",
    category: "New Era Drinks",
    glass: "Vaso Tumbler",
    method: "Agitado",
    garnish: "Piel de limón y uvas",
    color: "#D4C78F",
    icon: "🍇",
    ingredients: ["45ml Grappa Blanca","22.5ml Zumo de Limón","15ml Mezcla de Miel y Manzanilla","15ml Cordial de Manzanilla","10ml Clara de Huevo (opcional)"],
    story: 'Cóctel italiano moderno que celebra la grappa del Véneto. La manzanilla le aporta un carácter floral delicado.',
  },
  {
    name: "Yellow Bird",
    category: "New Era Drinks",
    glass: "Copa de Cóctel",
    method: "Agitado",
    garnish: "Sin decoración",
    color: "#FFD700",
    icon: "🐦",
    ingredients: ["30ml Ron Blanco","15ml Galliano","15ml Triple Sec","15ml Zumo de Lima"],
    story: 'Cóctel tropical caribeño con el dulzor del Galliano y la frescura de la lima.',
  },
];
