// Derive the base path from the SW's own scope so this works both locally
// (scope = '/') and on GitHub Pages in a subdirectory (scope = '/Stirio/').
const BASE = new URL(self.registration.scope).pathname;

const CACHE_PATHS = [
  '',           // root (e.g. /Stirio/ or /)
  'index.html',
  'map.html',
  'favicon.svg',
  'logo.svg',
  'manifest.json',
  'css/style.css',
  'trivias/all.json',
  'trivias/general.json',
  'trivias/historia_cocteles.json',
  'trivias/quiensoy.json',
  'trivias/historia_iba_fabe.json',
  'flags/en.svg',
  'flags/es.svg',
  // JS modules
  'js/app.js',
  'js/utils.js',
  'js/rivals.js',
  'js/questions.js',
  'js/learn.js',
  'js/lang.js',
  'js/auth.js',
  'js/quiz.js',
  'js/leaderboard.js',
  'js/share.js',
  'js/achievements.js',
  'js/daily.js',
  'js/speed.js',
  'js/blind.js',
  'js/bot.js',
  'js/fichas.js',
  'js/fichas/index.js',
  'js/fichas/iba_unforgettables.js',
  'js/fichas/iba_contemporary.js',
  'js/fichas/iba_new_era.js',
  'js/fichas/diffords.js',
  'js/academy.js',
  'js/academy_data.js',
  'js/cookies.js',
  'js/constructor.js',
  'js/firebase-config.js',
  // Mini-games are a separate React + Three.js build under games-r3f-demo/.
  // The SPA navigates there directly (no iframe). We cache the entry file
  // and its hashed bundle so the games work offline.
  'games-r3f-demo/index.html',
  'games-r3f-demo/assets/index-B3AN0ER5.js',
  'games-r3f-demo/assets/open-sans-DRMBTUIL.ttf',
  // Wiki 3D modules
  'js/wiki.js',
  'js/wiki-data.js',
  'js/wiki-3d.js',
  'js/wiki-scenes.js',
  'js/wiki-map.js',
  // 3D model assets
  'models/alambique.glb',
  // i18n question bundles (contain the icon fields for Learn cards)
  'js/i18n/questions_es.js',
  'js/i18n/questions_en.js',
  'js/i18n/questions_de.js',
  'js/i18n/questions_fr.js',
  'js/i18n/questions_pt.js',
  'js/i18n/fichas_i18n.js',
  // Per-language translation files
  'i18n/es.json',
  'i18n/en.json',
  'i18n/fr.json',
  'i18n/pt.json',
  'i18n/de.json',
  // Design system v2 (React + Neon Lounge)
  'css/tokens.css',
  'js/repo-data.js',
  'js/data.js',
  'js/ficha-images.js',
  'js/ui.jsx',
  'js/lesson.jsx',
  'js/screens.jsx',
  'js/reference.jsx',
  'js/app.jsx',
  'js/legacy-modes.jsx',
  'js/duel.jsx',
  'js/glossary.jsx',
  'js/map.jsx',
  'js/library.jsx',
  'js/arcade.jsx',
  'js/memory.jsx',
  'js/rhythm.jsx',
  'wiki.html'
];

// Build full pathnames like /Stirio/index.html or /index.html
const CACHE_LIST = CACHE_PATHS.map(p => BASE + p);

const STATIC_CACHE_VERSION = `Stirio-v10.32`;
const DEBUG = false;

self.addEventListener('install', function(event) {
  if (DEBUG) {
    console.log(caches)
    console.log("SW Install Event: Is in the process");
  }

  // Skip the "waiting" phase — a new SW activates on the next navigation
  // instead of waiting for every tab/PWA instance to be closed first.
  self.skipWaiting();

  const onSuccessCachesOpen = (cache) => {
    if (DEBUG) {
      console.log(cache)
      console.log("SW Install Event: Successfully opened the cache and add the cache list");
    }

    return cache.addAll(CACHE_LIST)
  }

  // Works like async/await
  event.waitUntil(
    // caches is a global variable inside the service workers file [readily available]
    caches.open(STATIC_CACHE_VERSION).then(onSuccessCachesOpen)
  )
})


self.addEventListener('activate', (event) => {
  if (DEBUG) console.log("SW Activate Event: Is in the process")

  // Google Chrome browseer -> console -> application -> cache -> cache storage
  const onSuccessCachesKeys = (cacheNames) => {
    // List of cachenames generated by STATIC_CACHE_VERSION
    if (DEBUG) console.log(cacheNames)

    // Loop through all the keys stored in cache storage
    return Promise.all(
      cacheNames.map((cache) => {
        if (cache !== STATIC_CACHE_VERSION) {
          if (DEBUG) console.log(`SW Activate Event: Remove the cache: ${cache}`);
          return caches.delete(cache)
        }
      })
    )
  }

  event.waitUntil(Promise.all([
    // Delete stale caches
    caches.keys().then(onSuccessCachesKeys),
    // Take control of all open clients (tabs/PWA) immediately, so a
    // single reload picks up the new assets without needing to close tabs.
    self.clients.claim(),
  ]))
})

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
})

self.addEventListener('fetch', (event) => {
  const FALLBACK_URL = CACHE_LIST[0];
  if (DEBUG) console.log("SW Fetch Event: Is in the process");

  const onSuccessFetch = response => {
    if (CACHE_LIST.includes(new URL(event.request.url).pathname)) return response

    const onSuccessDynamicCacheOpen = cache => {
      cache.put(event.request.url, response.clone())
      return response
    }

    return caches
      .open(STATIC_CACHE_VERSION)
      .then(onSuccessDynamicCacheOpen)
      .catch(() => caches.match(FALLBACK_URL))
  }

  const onErrorFetch = () => {
    const onSuccessCacheMatch = response => {
      if (response) return response
      else return caches.match(FALLBACK_URL)
    }

    return caches.match(event.request).then(onSuccessCacheMatch)
  }

  event.respondWith(
      fetch(event.request)
      .then(onSuccessFetch)
      .catch(onErrorFetch)
  )
})
